### ISSUE TITLE
record-screen.sh is really useful

### ISSUE THREAD

**Issue by itf** [synaptiko/.files#3]
You record-screen.sh and its shortcut are really useful! 

It would be nice if they were in their own repo to make it easier to recommend / share with other people!

**Comment by synaptiko** [comment]
@itf Hey, unfortunately I do not use it anymore (I had some weird issues with conversion to gif and I gave up on it). But feel free to create your own repo or gist, if you are in need, here's the latest version I had: https://github.com/synaptiko/.files/blob/master~43/i3/record-screen.sh

Your are free to re-use whatever you need from this repo ;-) https://github.com/synaptiko/.files/blob/master/LICENSE
