### ISSUE TITLE
SSL issue on synaptiko repo

### ISSUE THREAD

**Issue by leabstrait** [synaptiko/.files#7]
Hi,

Getting this error when trying to install 

> `warning: database file for 'synaptiko' does not exist (use '-Sy' to download)`

and when trying to update:

>`yay -Sy
:: Synchronizing package databases...
 core is up to date
 extra is up to date
 community is up to date
error: failed retrieving file 'synaptiko.db' from arch-repo.synaptiko.cz : SSL: no alternative certificate subject name matches target host name 'arch-repo.synaptiko.cz'
error: failed retrieving file 'synaptiko.db' from arch-repo.omnia.synaptiko.cz : error:14094438:SSL routines:ssl3_read_bytes:tlsv1 alert internal error
error: failed to update synaptiko (download library error)
error: failed to synchronize all databases`

**Comment by synaptiko** [comment]
I'm sorry about that but you shouldn't use my repository directly. I'm doing a lot of changes here and I'll eventually move this repo out of GH and it won't be public anymore. It was never supposed to be used by other people.
